version: "3"
services:
  app:
    image: pudding/docker-app:docker-app-Folder-Namer-20250224.164759
    tty: true
    command: node /app/index.js "/input/__INPUT__"
    environment:
      - CONTAINER_NAME=docker-app-folder-namer-app
      - LOCAL_VOLUMN_PATH=/input/
      - RUN_COMMAND=node /app/index.js
    network_mode: host
    volumes: 
      - ./app:/app/
      - __SOURCE__:/input/
      - __SOURCE__:/output/